apiVersion: v1
kind: Service
metadata:
  name: control
  namespace: travel-control
  labels:
    app: control
    istio.io/ingress-use-waypoint: "true"
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: control